### ISSUE TITLE
Minha sugestão e 1 grimorio de gelo :D          Olha eu nao sei bem muito sobre black clover e então veio 1 grimorio da minha cabeça eu botei pois o unico grimorio que eu sei que tem no anime e o de 5 folhas que e anti-magia

### ISSUE THREAD

**Issue by maiconSpark1000** [RedeDark/CloverSuggestions#10]
## ✨ **| Qual é a sua sugestão?**

Sugestão incrível maravilhosa chocante que vai arrebentar o mundo...

## 🤔 **| Porque a sua sugestão deve ser adicionada no servidor?**

Texto texto texto texto texto...

## 📅 **| Considerações Finais**

Se você quiser colocar uma imagem de um gatinho muito fofo aqui, pode! Ou se não quiser, pode deletar esta seção...

**Comment by PeterStark000** [comment]
Cadê o resto da sugestão????

**Comment by PeterStark000** [comment]
Cadê o resto da sugestão????
