### ISSUE TITLE
Grimório tecnológico 

### ISSUE THREAD

**Issue by gokubr14** [RedeDark/CloverSuggestions#11]
Minha ideia seria fazer um grimório q n existe no anime um grimório tecnológico como se o cara pudesse hacker o seu grimório te silenciar usar uma espada meio q tecnológica e o modo final dele deixaria meio invuneravel por ataques físicos podem tomar dano apenas de ataques de grimório ou de ki

**Comment by PeterStark000** [comment]
É meio desconexo do anime
